begin;
do $$
declare a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();c uuid:=gen_random_uuid();v uuid:=gen_random_uuid();bv uuid:=gen_random_uuid();cv uuid:=gen_random_uuid();
 k uuid:=gen_random_uuid();r uuid:=gen_random_uuid();ev uuid:=gen_random_uuid();p uuid:=gen_random_uuid();t uuid:=gen_random_uuid();g uuid:=gen_random_uuid();q uuid;mid uuid;packet uuid:=gen_random_uuid();invitation uuid:=gen_random_uuid();result uuid;
 m jsonb;refs jsonb;reviewers jsonb;expected jsonb;amr jsonb;rd jsonb;gd jsonb;final_grant jsonb;
 e jsonb:='{"crypto_version":"leqvor-v5","algorithm":"AES-256-GCM","aad_version":1,"nonce":"AAAAAAAAAAAAAAAA","ciphertext":"AAAAAAAAAAAAAAAAAAAAAA=="}';
 pub jsonb:=jsonb_build_object('kty','EC','crv','P-256','x',repeat('A',43),'y',repeat('B',43));
begin
 insert into auth.users(id) values(a),(b),(c);
 insert into public.vaults(id,owner_id,wrapped_vmk_password,wrapped_vmk_recovery,kdf_salt,kdf_parameters,recovery_salt,crypto_version,recovery_verified_at) values(v,a,e,e,'fixture','{}','fixture','leqvor-v5',now()),(bv,b,e,e,'fixture','{}','fixture','leqvor-v5',now()),(cv,c,e,e,'fixture','{}','fixture','leqvor-v5',now());
 insert into public.user_sharing_keys(owner_id,vault_id,public_key,encrypted_private_key,crypto_version) values(b,bv,pub,e,'leqvor-v5'),(c,cv,pub,e,'leqvor-v5');
 insert into public.review_signing_keys(id,owner_id,vault_id,public_key,encrypted_metadata,encrypted_payload,wrapped_dek,crypto_version) values(k,b,bv,pub,e,e,e,'leqvor-v5');
 insert into public.records(id,owner_id,vault_id,encrypted_metadata,encrypted_payload,wrapped_dek,crypto_version) values(r,a,v,e,e,e,'leqvor-v5'),(ev,a,v,e,e,e,'leqvor-v5');
 insert into public.verification_policies(id,owner_id,vault_id,encrypted_metadata,encrypted_payload,wrapped_dek,crypto_version) values(p,a,v,e,e,e,'leqvor-v5');
 insert into public.trigger_rules(id,owner_id,vault_id,policy_id,record_id,encrypted_metadata,encrypted_payload,wrapped_dek,crypto_version) values(t,a,v,p,r,e,e,e,'leqvor-v5');
 insert into public.record_grants(id,owner_id,vault_id,record_id,recipient_id,encrypted_record_key,sender_public_material,permissions,grant_version,status,crypto_version,record_revision,expires_at) values(g,a,v,r,b,e,pub,'view',1,'active','leqvor-v5',1,now()+interval '1 day');
 refs:=jsonb_build_array(jsonb_build_object('record_id',ev,'record_revision',1,'requirement_index',0,'observed_at',now()));
 reviewers:=jsonb_build_array(jsonb_build_object('grant_id',g,'signing_key_id',k,'public_key',pub));
 amr:=jsonb_build_array(jsonb_build_object('method','password','timestamp',extract(epoch from now())::bigint));
 perform set_config('request.jwt.claim.sub',a::text,true);perform set_config('request.jwt.claims',jsonb_build_object('role','authenticated','aal','aal1','amr',amr)::text,true);execute 'set local role authenticated';
 m:=public.create_v5_trigger_manifest(t,1,30,1,reviewers,refs,jsonb_build_object('account_id',c,'public_key',pub));mid:=(m->>'id')::uuid;
 q:=public.request_v5_trigger_review(t,g,pub||jsonb_build_object('id',k),mid);
 rd:=jsonb_build_object('id',packet,'owner_id',a,'vault_id',v,'revision',1,'crypto_version','leqvor-v5','encrypted_metadata',e,'encrypted_payload',e);
 gd:=jsonb_build_object('id',gen_random_uuid(),'record_id',packet,'owner_id',a,'vault_id',v,'recipient_id',b,'permissions','view','grant_version',1,'crypto_version','leqvor-v5','salt',repeat('A',22)||'==','sender_public_material',pub,'encrypted_record_key',e);
 begin perform public.deliver_v5_trigger_review(q,rd||jsonb_build_object('plaintext','secret'),gd);raise exception 'FAIL plaintext context accepted';exception when invalid_parameter_value then null;end;
 perform public.deliver_v5_trigger_review(q,rd,gd);
 begin perform public.deliver_v5_trigger_review(q,rd,gd);raise exception 'FAIL mutable context';exception when unique_violation then null;end;
 perform set_config('request.jwt.claim.sub',c::text,true);
 begin perform public.read_v5_trigger_review(q);raise exception 'FAIL foreign context read';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claim.sub',b::text,true);
 if public.read_v5_trigger_review(q)->'record'->>'id'<>packet::text then raise exception 'FAIL selected delivery';end if;
 begin perform 1 from public.trigger_review_packets;raise exception 'FAIL direct packet access';exception when insufficient_privilege then null;end;
 execute 'reset role';select to_jsonb(x) into expected from public.trigger_review_requests x where id=q;
 perform set_config('request.jwt.claims','{"role":"service_role"}',true);execute 'set local role service_role';
 perform public.record_verified_v5_trigger_decision(b,amr,'aal1',expected,'APPROVED',repeat('A',86)||'==');
 execute 'reset role';perform set_config('request.jwt.claim.sub',a::text,true);perform set_config('request.jwt.claims',jsonb_build_object('role','authenticated','aal','aal1','amr',amr)::text,true);execute 'set local role authenticated';
 final_grant:=jsonb_build_object('id',invitation,'record_id',r,'owner_id',a,'vault_id',v,'recipient_id',c,'permissions','view','grant_version',1,'crypto_version','leqvor-v5','salt',repeat('A',22)||'==','sender_public_material',pub,'encrypted_record_key',e);
 begin perform public.authorize_v5_reviewed_invitation(mid,jsonb_set(final_grant,'{recipient_id}',to_jsonb(b)),pub);raise exception 'FAIL recipient substitution';exception when insufficient_privilege then null;end;
 execute 'reset role';update public.record_grants set status='revoked' where id=g;execute 'set local role authenticated';
 begin perform public.authorize_v5_reviewed_invitation(mid,final_grant,pub);raise exception 'FAIL revoked approval';exception when insufficient_privilege then null;end;
 execute 'reset role';update public.record_grants set status='active' where id=g;execute 'set local role authenticated';
 result:=public.authorize_v5_reviewed_invitation(mid,final_grant,pub);
 if result<>invitation or not exists(select 1 from public.record_grants where id=result and status='pending') then raise exception 'FAIL explicit pending invitation';end if;
 begin perform public.authorize_v5_reviewed_invitation(mid,final_grant,pub);raise exception 'FAIL replay';exception when insufficient_privilege then null;end;
 execute 'reset role';update public.record_grants set status='revoked' where id=g;execute 'set local role authenticated';perform set_config('request.jwt.claim.sub',b::text,true);
 begin perform public.read_v5_trigger_review(q);raise exception 'FAIL revoked context delivery';exception when insufficient_privilege then null;end;
 execute 'reset role';
 if has_function_privilege('authenticated','public.v5_create_manifest_internal(uuid,integer,integer,integer,jsonb,jsonb)','execute') then raise exception 'FAIL unpinned manifest bypass';end if;
end $$;
rollback;
