begin;
do $$
declare a uuid:=gen_random_uuid(); b uuid:=gen_random_uuid(); c uuid:=gen_random_uuid(); v uuid:=gen_random_uuid(); bv uuid:=gen_random_uuid(); r uuid:=gen_random_uuid(); invitation uuid:=gen_random_uuid();
 e jsonb:='{"crypto_version":"leqvor-v5","algorithm":"AES-256-GCM","aad_version":1,"nonce":"AAAAAAAAAAAAAAAA","ciphertext":"AAAAAAAAAAAAAAAAAAAAAA=="}';
 pub jsonb:=jsonb_build_object('kty','EC','crv','P-256','x',repeat('A',43),'y',repeat('B',43)); g jsonb; bundle jsonb;
begin
 insert into auth.users(id) values(a),(b),(c);
 insert into public.vaults(id,owner_id,wrapped_vmk_password,wrapped_vmk_recovery,kdf_salt,kdf_parameters,recovery_salt,crypto_version,recovery_verified_at) values(v,a,e,e,'fixture','{}','fixture','leqvor-v5',now()),(bv,b,e,e,'fixture','{}','fixture','leqvor-v5',now());
 insert into public.records(id,owner_id,vault_id,encrypted_metadata,encrypted_payload,wrapped_dek,crypto_version) values(r,a,v,e,e,e,'leqvor-v5');
 insert into public.user_sharing_keys(owner_id,vault_id,public_key,encrypted_private_key,crypto_version) values(b,bv,pub,e,'leqvor-v5');
 g:=jsonb_build_object('id',invitation,'record_id',r,'owner_id',a,'vault_id',v,'recipient_id',b,'permissions','view','grant_version',1,'crypto_version','leqvor-v5','salt','AAAAAAAAAAAAAAAAAAAAAA==','sender_public_material',pub,'encrypted_record_key',e);
 perform set_config('request.jwt.claim.sub',a::text,true);execute 'set local role authenticated';
 begin perform public.invite_v5_record(g,1,pub);raise exception 'FAIL missing recent auth';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claims',jsonb_build_object('aal','aal1','amr',jsonb_build_array(jsonb_build_object('method','password','timestamp',extract(epoch from now())::bigint)))::text,true);
 begin perform public.invite_v5_record(g,2,pub);raise exception 'FAIL stale record';exception when serialization_failure then null;end;
 begin perform public.invite_v5_record(g,null,pub);raise exception 'FAIL missing revision';exception when serialization_failure then null;end;
 begin perform public.invite_v5_record(g,1,jsonb_set(pub,'{x}',to_jsonb(repeat('C',43))));raise exception 'FAIL key substitution';exception when invalid_parameter_value then null;end;
 perform public.invite_v5_record(g,1,pub);
 begin perform public.accept_v5_share(invitation);raise exception 'FAIL sender acceptance';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claim.sub',c::text,true);
 if jsonb_array_length(public.list_v5_shares())<>0 then raise exception 'FAIL unrelated list';end if;
 begin perform public.read_v5_share(invitation);raise exception 'FAIL unrelated read';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claim.sub',b::text,true);
 if (select count(*) from public.records where id=r)<>0 or (select count(*) from public.record_grants where id=invitation)<>0 then raise exception 'FAIL broad recipient access';end if;
 begin perform public.read_v5_share(invitation);raise exception 'FAIL pending read';exception when insufficient_privilege then null;end;
 perform public.accept_v5_share(invitation);
 begin perform public.accept_v5_share(invitation);raise exception 'FAIL replay acceptance';exception when insufficient_privilege then null;end;
 bundle:=public.read_v5_share(invitation);
 if bundle->'record' ? 'wrapped_dek' or bundle->'record'->>'revision'<>'1' then raise exception 'FAIL snapshot boundary';end if;
 begin perform public.revoke_v5_share(invitation);raise exception 'FAIL recipient revocation';exception when insufficient_privilege then null;end;
 execute 'reset role';
 update public.record_grants set expires_at=now()-interval '1 minute' where id=invitation;
 execute 'set local role authenticated';
 begin perform public.read_v5_share(invitation);raise exception 'FAIL expired read';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claim.sub',a::text,true);perform public.revoke_v5_share(invitation);
 perform set_config('request.jwt.claim.sub',b::text,true);
 begin perform public.read_v5_share(invitation);raise exception 'FAIL revoked read';exception when insufficient_privilege then null;end;
 execute 'reset role';
 insert into auth.mfa_factors(id,user_id,status) values(gen_random_uuid(),a,'verified');
 perform set_config('request.jwt.claim.sub',a::text,true);execute 'set local role authenticated';
 begin perform public.invite_v5_record(jsonb_set(g,'{id}',to_jsonb(gen_random_uuid())),1,pub);raise exception 'FAIL MFA bypass';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claims',jsonb_build_object('amr',jsonb_build_array(jsonb_build_object('method','password','timestamp',extract(epoch from now())::bigint)))::text,true);
 begin perform public.invite_v5_record(jsonb_set(g,'{id}',to_jsonb(gen_random_uuid())),1,pub);raise exception 'FAIL missing MFA assurance';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claims',jsonb_build_object('aal','aal2','amr',jsonb_build_array(jsonb_build_object('method','password','timestamp',extract(epoch from now())::bigint-600)))::text,true);
 begin perform public.invite_v5_record(jsonb_set(g,'{id}',to_jsonb(gen_random_uuid())),1,pub);raise exception 'FAIL stale authentication';exception when insufficient_privilege then null;end;
end $$;
reset role;
rollback;
