begin;
do $$
declare
 a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();c uuid:=gen_random_uuid();v uuid:=gen_random_uuid();bv uuid:=gen_random_uuid();
 r uuid:=gen_random_uuid();other_record uuid:=gen_random_uuid();p uuid:=gen_random_uuid();t uuid:=gen_random_uuid();g uuid:=gen_random_uuid();g2 uuid:=gen_random_uuid();q uuid;q2 uuid;
 e jsonb:='{"crypto_version":"leqvor-v5","algorithm":"AES-256-GCM","aad_version":1,"nonce":"AAAAAAAAAAAAAAAA","ciphertext":"AAAAAAAAAAAAAAAAAAAAAA=="}';
 pub jsonb:=jsonb_build_object('kty','EC','crv','P-256','x',repeat('A',43),'y',repeat('B',43));
 signer uuid:=gen_random_uuid();expected jsonb;sig text:=repeat('A',86)||'==';
 recent jsonb:=jsonb_build_object('aal','aal1','amr',jsonb_build_array(jsonb_build_object('method','password','timestamp',extract(epoch from now())::bigint)));
begin
 insert into auth.users(id) values(a),(b),(c);
 insert into public.vaults(id,owner_id,wrapped_vmk_password,wrapped_vmk_recovery,kdf_salt,kdf_parameters,recovery_salt,crypto_version,recovery_verified_at) values(v,a,e,e,'fixture','{}','fixture','leqvor-v5',now()),(bv,b,e,e,'fixture','{}','fixture','leqvor-v5',now());
 insert into public.user_sharing_keys(owner_id,vault_id,public_key,encrypted_private_key,crypto_version) values(b,bv,pub,e,'leqvor-v5');
 insert into public.records(id,owner_id,vault_id,encrypted_metadata,encrypted_payload,wrapped_dek,crypto_version) values(r,a,v,e,e,e,'leqvor-v5'),(other_record,a,v,e,e,e,'leqvor-v5');
 insert into public.verification_policies(id,owner_id,vault_id,encrypted_metadata,encrypted_payload,wrapped_dek,crypto_version) values(p,a,v,e,e,e,'leqvor-v5');
 insert into public.trigger_rules(id,owner_id,vault_id,policy_id,record_id,encrypted_metadata,encrypted_payload,wrapped_dek,crypto_version) values(t,a,v,p,r,e,e,e,'leqvor-v5');
 insert into public.review_signing_keys(id,owner_id,vault_id,public_key,encrypted_metadata,encrypted_payload,wrapped_dek,crypto_version) values(signer,b,bv,pub,e,e,e,'leqvor-v5'); expected:=pub||jsonb_build_object('id',signer);
 perform set_config('request.jwt.claim.sub',a::text,true);perform set_config('request.jwt.claims',recent::text,true);execute 'set local role authenticated';
 perform public.invite_v5_record(jsonb_build_object('id',g,'record_id',r,'owner_id',a,'vault_id',v,'recipient_id',b,'permissions','view','grant_version',1,'crypto_version','leqvor-v5','salt','AAAAAAAAAAAAAAAAAAAAAA==','sender_public_material',pub,'encrypted_record_key',e),1,pub);
 perform public.invite_v5_record(jsonb_build_object('id',g2,'record_id',other_record,'owner_id',a,'vault_id',v,'recipient_id',b,'permissions','view','grant_version',1,'crypto_version','leqvor-v5','salt','AAAAAAAAAAAAAAAAAAAAAA==','sender_public_material',pub,'encrypted_record_key',e),1,pub);
 begin perform public.request_v5_trigger_review(t,g,expected);raise exception 'FAIL pending share';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claim.sub',b::text,true);perform public.accept_v5_share(g);perform public.accept_v5_share(g2);
 begin perform public.request_v5_trigger_review(t,g,expected);raise exception 'FAIL recipient requests owner rule';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claim.sub',a::text,true);
 begin perform public.request_v5_trigger_review(t,g2,expected);raise exception 'FAIL different record';exception when insufficient_privilege then null;end;
 q:=public.request_v5_trigger_review(t,g,expected);
 if not exists(select 1 from public.trigger_review_requests where id=q and record_revision=1 and expires_at<=now()+interval '7 days') then raise exception 'FAIL bounded request';end if;
 begin perform public.request_v5_trigger_review(t,g,expected);raise exception 'FAIL duplicate request';exception when invalid_parameter_value then null;end;
 begin perform public.decide_v5_trigger_review(q,'APPROVED',sig);raise exception 'FAIL owner decision';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claim.sub',c::text,true);
 if exists(select 1 from public.trigger_review_requests where id=q) then raise exception 'FAIL unrelated request read';end if;
 begin perform public.decide_v5_trigger_review(q,'APPROVED',sig);raise exception 'FAIL unrelated decision';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claim.sub',b::text,true);
 if exists(select 1 from public.trigger_rules where id=t) or exists(select 1 from public.verification_policies where id=p) then raise exception 'FAIL recipient planning access';end if;
 perform set_config('request.jwt.claims','{}',true);
 begin perform public.decide_v5_trigger_review(q,'APPROVED',sig);raise exception 'FAIL missing reauth';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claims',recent::text,true);
 begin perform public.decide_v5_trigger_review(q,null,sig);raise exception 'FAIL null decision';exception when invalid_parameter_value then null;end;
 begin perform public.cancel_v5_trigger_review(q);raise exception 'FAIL recipient cancel';exception when insufficient_privilege then null;end;
 perform public.decide_v5_trigger_review(q,'APPROVED',sig);
 begin perform public.decide_v5_trigger_review(q,'REJECTED',sig);raise exception 'FAIL replay';exception when invalid_parameter_value then null;end;
 if not exists(select 1 from public.trigger_reviewer_decisions where request_id=q and reviewer_id=b and outcome='APPROVED') then raise exception 'FAIL captured identity';end if;
 begin update public.trigger_reviewer_decisions set outcome='REJECTED' where request_id=q;raise exception 'FAIL decision rewrite';exception when insufficient_privilege then null;end;
 begin insert into public.trigger_reviewer_decisions(request_id,reviewer_id,outcome,created_at) values(gen_random_uuid(),b,'APPROVED',now());raise exception 'FAIL direct decision';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claim.sub',c::text,true);
 if exists(select 1 from public.trigger_reviewer_decisions where request_id=q) then raise exception 'FAIL unrelated history';end if;
 perform set_config('request.jwt.claim.sub',a::text,true);
 perform public.cancel_v5_trigger_review(q);q2:=public.request_v5_trigger_review(t,g,expected);
 if (select status from public.trigger_rules where id=t)<>'DRAFT' or (select count(*) from public.record_grants where record_id=r)<>1 then raise exception 'FAIL approval activated';end if;
 execute 'reset role';update public.trigger_review_requests set expires_at=now()-interval '1 second' where id=q2;execute 'set local role authenticated';
 perform set_config('request.jwt.claim.sub',b::text,true);
 begin perform public.decide_v5_trigger_review(q2,'APPROVED',sig);raise exception 'FAIL expired';exception when insufficient_privilege then null;end;
 begin perform public.decide_v5_trigger_review(q,'APPROVED',sig);raise exception 'FAIL cancelled';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claim.sub',a::text,true);q2:=public.request_v5_trigger_review(t,g,expected);perform public.revoke_v5_share(g);
 perform set_config('request.jwt.claim.sub',b::text,true);
 begin perform public.decide_v5_trigger_review(q2,'APPROVED',sig);raise exception 'FAIL revoked share';exception when insufficient_privilege then null;end;
 execute 'reset role';
 update public.record_grants set status='active',expires_at=null where id=g;
 execute 'set local role authenticated';
 begin perform public.decide_v5_trigger_review(q2,'APPROVED',sig);raise exception 'FAIL missing grant expiry';exception when insufficient_privilege then null;end;
 execute 'reset role';update public.record_grants set expires_at=now()+interval '1 day' where id=g;
 insert into auth.mfa_factors(id,user_id,status) values(gen_random_uuid(),b,'verified');
 update public.record_grants set status='active' where id=g;
 execute 'set local role authenticated';
 begin perform public.decide_v5_trigger_review(q2,'APPROVED',sig);raise exception 'FAIL MFA bypass';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claims',jsonb_set(recent,'{aal}','"aal2"')::text,true);perform public.decide_v5_trigger_review(q2,'REJECTED',sig);
 execute 'reset role';
 if has_table_privilege('anon','public.trigger_review_requests','select') or has_table_privilege('authenticated','public.trigger_review_requests','insert') then raise exception 'FAIL privileges';end if;
 delete from public.vaults where id=v;
 if exists(select 1 from public.trigger_reviewer_decisions where request_id=q) then raise exception 'FAIL deletion lifecycle';end if;
end $$;
rollback;
