begin;
do $$
declare
 a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();c uuid:=gen_random_uuid();v uuid:=gen_random_uuid();bv uuid:=gen_random_uuid();cv uuid:=gen_random_uuid();
 k1 uuid:=gen_random_uuid();k2 uuid:=gen_random_uuid();r uuid:=gen_random_uuid();ev uuid:=gen_random_uuid();p uuid:=gen_random_uuid();t uuid:=gen_random_uuid();g1 uuid:=gen_random_uuid();g2 uuid:=gen_random_uuid();q1 uuid;q2 uuid;mid uuid;m jsonb;refs jsonb;reviewers jsonb;expected jsonb;readiness_result jsonb;amr jsonb;sig text:=repeat('A',86)||'==';
 e jsonb:='{"crypto_version":"leqvor-v5","algorithm":"AES-256-GCM","aad_version":1,"nonce":"AAAAAAAAAAAAAAAA","ciphertext":"AAAAAAAAAAAAAAAAAAAAAA=="}';
 pub jsonb:=jsonb_build_object('kty','EC','crv','P-256','x',repeat('A',43),'y',repeat('B',43));
begin
 insert into auth.users(id) values(a),(b),(c);
 insert into public.vaults(id,owner_id,wrapped_vmk_password,wrapped_vmk_recovery,kdf_salt,kdf_parameters,recovery_salt,crypto_version,recovery_verified_at) values(v,a,e,e,'fixture','{}','fixture','leqvor-v5',now()),(bv,b,e,e,'fixture','{}','fixture','leqvor-v5',now()),(cv,c,e,e,'fixture','{}','fixture','leqvor-v5',now());
 insert into public.user_sharing_keys(owner_id,vault_id,public_key,encrypted_private_key,crypto_version) values(b,bv,pub,e,'leqvor-v5'),(c,cv,pub,e,'leqvor-v5');
 insert into public.review_signing_keys(id,owner_id,vault_id,public_key,encrypted_metadata,encrypted_payload,wrapped_dek,crypto_version) values(k1,b,bv,pub,e,e,e,'leqvor-v5'),(k2,c,cv,pub,e,e,e,'leqvor-v5');
 insert into public.records(id,owner_id,vault_id,encrypted_metadata,encrypted_payload,wrapped_dek,crypto_version) values(r,a,v,e,e,e,'leqvor-v5'),(ev,a,v,e,e,e,'leqvor-v5');
 insert into public.verification_policies(id,owner_id,vault_id,encrypted_metadata,encrypted_payload,wrapped_dek,crypto_version) values(p,a,v,e,e,e,'leqvor-v5');
 insert into public.trigger_rules(id,owner_id,vault_id,policy_id,record_id,encrypted_metadata,encrypted_payload,wrapped_dek,crypto_version) values(t,a,v,p,r,e,e,e,'leqvor-v5');
 insert into public.record_grants(id,owner_id,vault_id,record_id,recipient_id,encrypted_record_key,sender_public_material,permissions,grant_version,status,crypto_version,record_revision,expires_at) values(g1,a,v,r,b,e,pub,'view',1,'active','leqvor-v5',1,now()+interval '1 day'),(g2,a,v,r,c,e,pub,'view',1,'active','leqvor-v5',1,now()+interval '1 day');
 refs:=jsonb_build_array(jsonb_build_object('record_id',ev,'record_revision',1,'requirement_index',0,'observed_at',now()));
 reviewers:=jsonb_build_array(jsonb_build_object('grant_id',g1,'signing_key_id',k1,'public_key',pub),jsonb_build_object('grant_id',g2,'signing_key_id',k2,'public_key',pub));
 amr:=jsonb_build_array(jsonb_build_object('method','password','timestamp',extract(epoch from now())::bigint));
 perform set_config('request.jwt.claim.sub',a::text,true);perform set_config('request.jwt.claims',jsonb_build_object('role','authenticated','aal','aal1','amr',amr)::text,true);execute 'set local role authenticated';
 begin perform public.create_v5_trigger_manifest(t,3,30,1,reviewers,refs);raise exception 'FAIL impossible threshold';exception when invalid_parameter_value then null;end;
 begin perform public.create_v5_trigger_manifest(t,2,30,1,jsonb_build_array(reviewers->0,reviewers->0),refs);raise exception 'FAIL duplicate account';exception when insufficient_privilege then null;end;
 begin perform public.create_v5_trigger_manifest(t,2,30,1,reviewers,jsonb_set(refs,'{0,record_revision}','2'));raise exception 'FAIL stale evidence revision';exception when insufficient_privilege then null;end;
 begin perform public.create_v5_trigger_manifest(t,2,30,1,reviewers,jsonb_set(refs,'{0,observed_at}',to_jsonb(now()+interval '1 day')));raise exception 'FAIL future evidence';exception when insufficient_privilege then null;end;
 m:=public.create_v5_trigger_manifest(t,2,30,1,reviewers,refs);mid:=(m->>'id')::uuid;
 if length(m->>'manifest_hash')<>64 or m->'snapshot'->'record' ? 'wrapped_dek' then raise exception 'FAIL commitment boundary';end if;
 if public.v5_trigger_manifest_readiness(mid)->>'state'<>'NEEDS_REVIEW' then raise exception 'FAIL initial readiness';end if;
 q1:=public.request_v5_trigger_review(t,g1,pub||jsonb_build_object('id',k1),mid);q2:=public.request_v5_trigger_review(t,g2,pub||jsonb_build_object('id',k2),mid);
 begin update public.trigger_manifests set minimum_approvals=1 where id=mid;raise exception 'FAIL mutable threshold';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claim.sub',b::text,true);
 if exists(select 1 from public.trigger_manifests where id=mid) then raise exception 'FAIL broad recipient snapshot';end if;
 begin perform public.v5_trigger_manifest_readiness(mid);raise exception 'FAIL foreign readiness';exception when insufficient_privilege then null;end;
 execute 'reset role';perform set_config('request.jwt.claims','{"role":"service_role"}',true);
 select to_jsonb(x) into expected from public.trigger_review_requests x where id=q1;execute 'set local role service_role';
 begin perform public.record_verified_v5_trigger_decision(b,amr,'aal1',jsonb_set(expected,'{manifest_hash}',to_jsonb(repeat('b',64))),'APPROVED',sig);raise exception 'FAIL manifest signature context';exception when insufficient_privilege then null;end;
 perform public.record_verified_v5_trigger_decision(b,amr,'aal1',expected,'APPROVED',sig);
 execute 'reset role';perform set_config('request.jwt.claim.sub',a::text,true);execute 'set local role authenticated';
 readiness_result:=public.v5_trigger_manifest_readiness(mid);if readiness_result->>'state'<>'NEEDS_REVIEW' or readiness_result->>'approvals'<>'1' then raise exception 'FAIL minimum threshold';end if;
 execute 'reset role';perform set_config('request.jwt.claims','{"role":"service_role"}',true);select to_jsonb(x) into expected from public.trigger_review_requests x where id=q2;execute 'set local role service_role';
 perform public.record_verified_v5_trigger_decision(c,amr,'aal1',expected,'APPROVED',sig);execute 'reset role';perform set_config('request.jwt.claim.sub',a::text,true);execute 'set local role authenticated';
 readiness_result:=public.v5_trigger_manifest_readiness(mid);if readiness_result->>'state'<>'READY_FOR_OWNER_REVIEW' or readiness_result->>'approvals'<>'2' or readiness_result->>'activation_enabled'<>'false' then raise exception 'FAIL administrative threshold';end if;
 execute 'reset role';update public.record_grants set status='revoked' where id=g1;execute 'set local role authenticated';
 if public.v5_trigger_manifest_readiness(mid)->>'state'<>'NEEDS_REVIEW' then raise exception 'FAIL revoked approval counted';end if;
 execute 'reset role';update public.record_grants set status='active' where id=g1;delete from public.user_sharing_keys where owner_id=b;execute 'set local role authenticated';
 if public.v5_trigger_manifest_readiness(mid)->>'state'<>'NEEDS_REVIEW' then raise exception 'FAIL removed sharing identity counted';end if;
 execute 'reset role';insert into public.user_sharing_keys(owner_id,vault_id,public_key,encrypted_private_key,crypto_version) values(b,bv,pub,e,'leqvor-v5');execute 'set local role authenticated';
 execute 'reset role';update public.record_grants set status='active' where id=g1;update public.trigger_reviewer_decisions set outcome='REJECTED' where request_id=q2;execute 'set local role authenticated';
 if public.v5_trigger_manifest_readiness(mid)->>'state'<>'BLOCKED' then raise exception 'FAIL rejection';end if;
 execute 'reset role';update public.trigger_reviewer_decisions set outcome='APPROVED',server_signature_verified=false where request_id=q2;execute 'set local role authenticated';
 if public.v5_trigger_manifest_readiness(mid)->>'state'<>'NEEDS_REVIEW' then raise exception 'FAIL unsigned approval counted';end if;
 execute 'reset role';update public.records set revision=2 where id=ev;execute 'set local role authenticated';
 if public.v5_trigger_manifest_readiness(mid)->>'state'<>'STALE' then raise exception 'FAIL evidence revision drift';end if;
 execute 'reset role';update public.records set revision=1 where id=ev;update public.records set revision=2 where id=r;execute 'set local role authenticated';
 if public.v5_trigger_manifest_readiness(mid)->>'state'<>'STALE' then raise exception 'FAIL target revision drift';end if;
 execute 'reset role';update public.records set revision=1 where id=r;update public.trigger_manifests set snapshot=jsonb_set(snapshot,'{expires_at}',to_jsonb(now()-interval '1 second')),expires_at=now()-interval '1 second' where id=mid;
 update public.trigger_manifests set manifest_hash=encode(sha256(convert_to(snapshot::text,'UTF8')),'hex') where id=mid;execute 'set local role authenticated';
 if public.v5_trigger_manifest_readiness(mid)->>'state'<>'EXPIRED' then raise exception 'FAIL evidence deadline';end if;
 execute 'reset role';
 if (select status from public.trigger_rules where id=t)<>'DRAFT' or has_function_privilege('authenticated','public.v5_request_pinned_trigger_review_internal(uuid,uuid,jsonb)','execute') then raise exception 'FAIL activation/bypass';end if;
end $$;
rollback;
