import {useEffect,useRef,useState} from 'react';
import {Button} from '../ui/Primitives';
import {safeFailure} from '../../modules/security/safeEvents';
import {DocumentLinksView} from './DocumentFields';
export default function DocumentHistory({record,service,people,records,onDownload}){
 const [versions,setVersions]=useState(null),[selected,setSelected]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),active=useRef(true);
 useEffect(()=>{active.current=true;return()=>{active.current=false;};},[]);
 async function load(){setBusy(true);setError('');try{const rows=await service.versions(record);if(active.current)setVersions(rows);}catch(e){if(active.current)setError(safeFailure(e));}finally{if(active.current)setBusy(false);}}
 async function reveal(version){setBusy(true);setError('');setSelected(null);try{const payload=await service.reveal(version.snapshot);if(active.current)setSelected({version,payload});}catch(e){if(active.current)setError(safeFailure(e));}finally{if(active.current)setBusy(false);}}
 return <section><h3>Encrypted version history</h3><p className="field-hint">Saved revisions cannot be edited in this history. Only the current revision is available for records created before history was enabled. Deleting a record deletes its history. These snapshots are not digitally signed.</p>{error&&<p role="alert">{error}</p>}<Button disabled={busy} onClick={load}>Load saved revisions</Button>{versions&&<ul>{versions.map(version=><li key={version.revision}>Revision {version.revision} · {version.captured_at} <Button disabled={busy} onClick={()=>reveal(version)}>Reveal revision {version.revision}</Button></li>)}</ul>}{selected&&<div><h4>Read-only revision {selected.version.revision}</h4><p>Original location: {selected.payload.original_location||'Not recorded'}</p><p>Description: {selected.payload.description||'Not recorded'}</p><p>Instructions: {selected.payload.instructions||'Not recorded'}</p><p>Execution status: {selected.payload.continuity_details?.document?.execution_status||'Unknown'}</p><DocumentLinksView value={selected.payload.continuity_details?.document} people={people} records={records}/>{selected.version.files.map((file,index)=><Button key={file.id} disabled={busy} onClick={()=>onDownload(file)}>Download revision attachment {index+1}</Button>)}<Button onClick={()=>setSelected(null)}>Hide revision</Button></div>}</section>;
}
