import { useState } from 'react';
import { Heading, Card, Button, Badge, Empty } from '../components/ui/Primitives';
import Icon from '../components/Icon';
import { insurancePolicies, coverageFacts, claimReadiness, isInsuranceAsset } from '../modules/insurance/continuity';
import { ClaimChecklist } from '../components/records/InsuranceSummary';
export default function Insurance({ records, people, go, demo }) {
  const [selectedId, setSelectedId] = useState(null);
  const policies = insurancePolicies(records), selected = policies.find(p => p.id === selectedId) || policies[0];
  const assets = records.filter(isInsuranceAsset);
  return <><Heading eyebrow="YOUR VAULT / INSURANCE" title="Insurance, ready for continuity." text="Help your family understand what exists and where to begin."><Button variant="primary" icon="plus" onClick={() => go('/app/vault/new/insurance')}>Add Policy</Button></Heading><p className="insurance-scope">Policy records, documents, people, and instructions — organized together. {demo && 'Fictional sample information.'}</p><div className="insurance-hub"><Card><div className="panel-heading"><h2>Your policies</h2><Badge>{policies.length} records</Badge></div>{policies.length ? policies.map(p => {const r = claimReadiness(p,people);return <button key={p.id} className={'policy-row '+(selected?.id === p.id?'selected':'')} onClick={() => setSelectedId(p.id)}><span className="icon-tile"><Icon name="shield"/></span><span><strong>{p.title}</strong><small>{p.insurance_index?.policy_status || 'Status not recorded'} · {r.completed}/{r.total} checklist items recorded</small></span><Icon name="chevron"/></button>;}) : <Empty title="Keep the first policy within reach" text="Add policy details and link the people and assets it relates to."><Button onClick={() => go('/app/vault/new/insurance')}>Add Policy</Button></Empty>}<h2 className="coverage-heading">Coverage Map</h2><p className="field-hint">Links and missing information only. Active status is recorded by the owner, not verified with an insurer.</p>{assets.length ? assets.map(a => <div className="coverage-row" key={a.id}><button className="text-button" onClick={() => go('/app/vault/'+a.id)}>{a.title} ›</button><div>{coverageFacts(records,a.id).map(f => <span key={f}>{f}</span>)}</div></div>) : <p className="muted">Add an asset to start linking policy records.</p>}</Card><Card>{selected ? <><div className="panel-heading"><h2>{selected.title}</h2><Icon name="lock"/></div><ClaimChecklist record={selected} people={people}/><Button variant="primary" onClick={() => go('/app/vault/'+selected.id)}>Open policy record <Icon name="arrow"/></Button><p className="field-hint">Policy numbers, renewal dates, and instructions require deliberate reveal.</p><div className="insurance-roles">{[['Owner',[selected.insurance_index?.owner_id]],['Insured',selected.insurance_index?.insured_ids],['Beneficiary',selected.insurance_index?.beneficiary_ids],['Trusted contact',selected.insurance_index?.trusted_ids]].map(([role,ids]) => <div key={role}><h3>{role}</h3><p>{(ids||[]).filter(Boolean).map(id => id === 'self'?'You':people.find(p => p.id===id)?.display_name||'Linked person unavailable').join(', ')||'Not recorded'}</p></div>)}</div><p className="field-hint">Policy roles and relationships do not grant access.</p></> : <Empty title="Select a policy" text="Its administrative checklist will appear here."/>}</Card></div></>;
}

