export const legalVersion = '2026-10-04';
export const privacyContact = 'kalambeshounak@gmail.com';

export const legalPages = {
  '/privacy': [
    'Interim Privacy Notice',
    'Effective 4 October 2026 · Limited beta · Version 2026-10-04',
    [
      ['Scope and contact', 'This notice describes the current LEQVOR application at leqvor.vercel.app, offered under the LENVOR brand. Privacy, access, correction, deletion and complaint requests can be sent to kalambeshounak@gmail.com, our temporary contact. Final legal-operator details and the reviewed policy are still being prepared. This notice is not a certification of legal compliance.'],
      ['Before you use the beta', 'LEQVOR remains under development. Independent security review, hosted recovery and backup acceptance, and some access features are unfinished. Use sample or non-sensitive information during this beta, keep independent copies, and do not use it as your only store of essential documents.'],
      ['Account and operational information', 'Account email, a supplied profile name, authentication credentials or verification factors, account identifiers, session information and security events are processed to create and authenticate accounts, deliver service emails, maintain the service and prevent abuse. Infrastructure providers may process IP addresses, browser or device information, request timestamps and diagnostic logs. These operational details are not hidden by vault encryption.'],
      ['Vault information and encryption boundaries', 'The V5 client encrypts record titles, notes, instructions, relationship details, filenames and file contents before upload. The service stores ciphertext, wrapped keys, opaque identifiers, sizes, versions and timestamps. Older records may contain plaintext metadata until migrated. Encryption does not hide all metadata, protect a compromised device, or prevent someone who receives plaintext from retaining it. Do not send passwords, recovery phrases, keys or private documents in support email.'],
      ['Why information is used', 'Information is used to authenticate users, store and retrieve encrypted records, support recovery mechanisms, apply access rules, send requested account emails, investigate problems and respond to privacy or security requests. Account authentication and vault unlocking are separate; resetting an account password does not recover a lost vault secret.'],
      ['Providers and disclosures', 'Vercel hosts the website. Supabase provides account authentication, database and object storage. Google Gmail SMTP currently delivers authentication email and the temporary contact inbox is hosted by Google. Email providers process recipient addresses and message content, including authentication links; vault plaintext is not required for these emails. Information may also be disclosed where required by applicable law or necessary to investigate abuse. A user’s recorded family relationship alone does not grant access to records.'],
      ['Processing locations', 'The configured Supabase database region is Mumbai. Hosting, email delivery, support and provider operations may involve processing in other countries. We do not promise that all data stays in India. Provider notices linked below describe their own processing; they do not replace this notice.'],
      ['Browser storage, analytics and AI', 'Authentication uses browser storage to maintain sessions. Sign out on shared devices and protect access to your browser profile. The current secure application does not include advertising pixels, marketing analytics or AI analysis of vault contents. Hosting and authentication services still produce operational logs.'],
      ['Retention and deletion', 'Records remain stored until deleted or the service ends, subject to technical and legal requirements. Deleting a record can enqueue encrypted-file cleanup; a deployed cleanup schedule and cloud restore process have not yet been verified. We cannot currently promise immediate removal from every provider log or backup. A finalized retention schedule is pending. Contact us for account deletion or retention questions; do not assume signing out deletes your account.'],
      ['Your requests and choices', 'You can edit or delete records using available controls and request access, correction, export or deletion of account information through the contact below. Depending on applicable law, you may also have rights to object, restrict processing, withdraw consent where relied upon, or complain to a competent authority. We may need proportionate identity verification, but will never ask for your vault password or recovery phrase. Some requests may require manual handling; processing essential to the service cannot be stopped while continuing that service.'],
      ['Other people and children', 'The beta is intended for adults aged 18 or older. Do not create a child account or upload children’s or other people’s sensitive information during testing. Only provide information you are authorized to use. Contact us if information was supplied without appropriate authority.'],
      ['Changes to this notice', 'The effective date and version identify this interim notice. A reviewed policy will replace it. Material changes will be identified when published and, where required, communicated or presented for consent before new processing begins. An interim policy does not remove statutory rights or excuse security obligations.'],
    ],
  ],
  '/terms': [
    'Interim Terms of Use',
    'Effective 4 October 2026 · Limited beta · Version 2026-10-04',
    [
      ['Purpose and operator contact', 'LEQVOR, offered under the LENVOR brand, is a developing information-organizing and continuity service. These interim terms explain permitted use and current limitations. Contact kalambeshounak@gmail.com for questions. Final legal-operator details and reviewed terms remain pending. These terms do not claim to resolve every applicable legal requirement.'],
      ['Beta access', 'Use the beta only if you are at least 18 and authorized to provide the information involved. Features may change, be unavailable or contain errors. Keep independent copies and use sample or non-sensitive data while testing. The beta is not a substitute for a reliable backup or emergency service.'],
      ['Your information and account', 'You retain your rights in your content. You authorize the limited technical processing needed to store and deliver it through the service as described in the Privacy Notice. Keep account credentials and recovery secrets secure, supply accurate account information and report suspected unauthorized access. Do not share your passwords or recovery phrase with support.'],
      ['Recovery and access limitations', 'Loss of all usable vault secrets may make encrypted content unrecoverable. Account password reset is separate from vault recovery. Listing a person or beneficiary does not create access, inheritance rights or legal authority. Sharing and revocation must be explicitly supported and verified; revocation cannot erase information a recipient has already copied. Disabled or preview controls are not functioning security services.'],
      ['No professional advice', 'Records, family instructions, insurance details and completion indicators are organizational aids. They are not legal, tax, investment, insurance or medical advice, a valid will, an insurance claim determination, or a guarantee of entitlement or protection. Use qualified professionals and the relevant institution’s processes where needed.'],
      ['Acceptable use', 'Do not upload unlawful material, infringe others’ rights, impersonate someone, distribute malware, bypass access controls or probe other users’ data. Report suspected vulnerabilities without accessing or exposing private information. Testing beyond your own authorized data requires separate permission.'],
      ['Service limits and rights', 'No guarantee of uninterrupted availability, complete recovery or fitness for a particular purpose is made for this beta. These statements do not exclude mandatory consumer rights or any duty or liability that cannot lawfully be excluded. No blanket liability waiver, arbitration requirement or governing-law selection is introduced by these interim terms.'],
      ['Leaving the service', 'You may stop using LEQVOR and request account deletion through the privacy contact. Preserve an independent copy of information you need first. Deletion and retention limitations are described in the Privacy Notice. Access may be restricted when reasonably necessary to address abuse or security risks; this does not give permission to use content for unrelated purposes.'],
      ['Updates and charges', 'These terms do not introduce a payment obligation. Any future paid service requires separately disclosed pricing and applicable terms. Material changes to these terms will be identified by date and communicated or presented for acceptance where required; merely publishing an interim notice does not establish consent to unrelated processing.'],
    ],
  ],
};
